package cse561;


import java.awt.Dimension;
import java.awt.Point;

import GenCol.entity;
import SimpArcMod.genr;
import model.modeling.message;
import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class AuthenticationSystem extends ViewableDigraph {

	public AuthenticationSystem(){
		super("Authentication System");
		CoupledModelConstruct();
	}
	public AuthenticationSystem(String name) {
		super("Authentication System");
		CoupledModelConstruct();
	}

	private void CoupledModelConstruct() {
		// TODO Auto-generated method stub
		addInport("in");
		addInport("SecurityLevel");
		addInport("ApplicationName");
		addInport("PayloadSize");
		addOutport("out");
		addOutport("outCA");
		addOutport("outTC");
		
		AuthenticationManager am = new AuthenticationManager();
		AuthenticationFactorManager afm = new AuthenticationFactorManager();
		SymmetricEncryption se = new SymmetricEncryption();
		AsymmetricEncryption ae = new AsymmetricEncryption();
		CertificateAuthority ca = new CertificateAuthority(); 
		Transducer t = new Transducer();
	
		add(am);
		add(afm);
		add(se);
		add(ae);
		add(ca);
		add(t);
		
		addTestInput("start",new entity("20"));
		
		addCoupling(this,"SecurityLevel", am, "SecurityLevel");
		addCoupling(this,"ApplicationName", am, "ApplicationName");
		addCoupling(this,"PayloadSize", am, "PayloadSize");
		addCoupling(this, "in", am, "in");
		addCoupling(am, "out", afm, "in");	
		addCoupling(am, "out", se, "in");
		addCoupling(am, "out", ae, "in");
		addCoupling(am, "out", ca, "in");
		addCoupling(afm, "out", am, "inAFM");
		addCoupling(se,"out", am, "inSymmetric");
		addCoupling(ae,"out", am, "inAsymmetric");
		
		//Tranducers
		addCoupling(am, "out", t, "arriveAM");
		addCoupling(afm, "out", t, "arriveAFM");
		addCoupling(se, "out", t, "arriveSE");
		addCoupling(ae, "out", t, "arriveAE");
		addCoupling(ca, "out", t, "arriveCA");
	}
	
	public void  Deltext(double e, message x){
		
//		if (messageOnPort(x,"Securitylevel",0)){
//			 entity val = x.getValOnPort("SecurityLevel",0);
//			 holdIn("active",0);
//
//		}
	}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(756, 539);
        ((ViewableComponent)withName("Symmetric Encryption")).setPreferredLocation(new Point(281, 30));
        ((ViewableComponent)withName("Authentication Factor Manager")).setPreferredLocation(new Point(28, 127));
        ((ViewableComponent)withName("Authentication Manager")).setPreferredLocation(new Point(50, 306));
        ((ViewableComponent)withName("CA")).setPreferredLocation(new Point(50, 50));
        ((ViewableComponent)withName("Asymm Encryption")).setPreferredLocation(new Point(292, 122));
        ((ViewableComponent)withName("TRANSDUCER")).setPreferredLocation(new Point(381, 234));
    }
}
