package cse561;


import java.awt.Dimension;
import java.awt.Point;

import GenCol.entity;
import SimpArcMod.genr;
import model.modeling.message;
import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class Server extends ViewableDigraph {

	public Server(){
		super("Server");
		CoupledModelConstruct();
	}
	public Server(String name) {
		super("Server");
		CoupledModelConstruct();
	}

	private void CoupledModelConstruct() {
		// TODO Auto-generated method stub
		addInport("in");
		addOutport("out");
		
		TicketManager tm = new TicketManager();
		SessionManager sm = new SessionManager();
	
		add(tm);
		add(sm);
		
		//addTestInput("start",new entity("20"));
		
		
		addCoupling(this, "in", tm, "in");
		addCoupling(tm, "out", sm, "in");
		addCoupling(sm, "out", this, "out");
		
	}
	
//	public void  Deltext(double e, message x){
//		System.out.println("hello");
//		double num = getValOnPort
//	}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(250, 186);
        ((ViewableComponent)withName("Session Manager")).setPreferredLocation(new Point(-9, 108));
        ((ViewableComponent)withName("Ticket Manager")).setPreferredLocation(new Point(-6, 27));
    }
}
