package cse561;


import java.awt.Dimension;
import java.awt.Point;

import GenCol.entity;
import SimpArcMod.genr;
import model.modeling.message;
import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class SimulationSystem extends ViewableDigraph {

	public SimulationSystem(){
		super("Simulation System");
		CoupledModelConstruct();
	}
	public SimulationSystem(String name) {
		super(name);
		CoupledModelConstruct();
	}

	private void CoupledModelConstruct() {

		
		Application a = new Application();
		AuthenticationSystem as = new AuthenticationSystem();
		Server s = new Server();
		CertificateAuthority ca = new CertificateAuthority();
		TargetClient tc = new TargetClient();

		add(a);
		add(as);
		add(s);
		
		addTestInput("start",new entity("20"));
		
		addCoupling(a, "out", as, "in");
		addCoupling(a, "SecurityLevel", as, "SecurityLevel");
		addCoupling(a, "ApplicationName", as, "ApplicationName");
		addCoupling(a, "PayloadSize", as, "PayloadSize");
		addCoupling(as, "outServer", s, "in");
		addCoupling(as, "outCA", ca, "in");
		addCoupling(as, "outTC", tc, "in");
	
	}
	
//	public void  Deltext(double e, message x){
//		System.out.println("hello");
//		double num = getValOnPort
//	}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1533, 814);
        ((ViewableComponent)withName("Authentication System")).setPreferredLocation(new Point(241, 27));
        ((ViewableComponent)withName("Server")).setPreferredLocation(new Point(1024, 27));
        ((ViewableComponent)withName("Application")).setPreferredLocation(new Point(-6, 14));
    }
}
